# Generated by Django 4.2.30 on 2026-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('tech_stack', models.CharField(blank=True, help_text='e.g. Django, PostgreSQL, Docker', max_length=300, verbose_name='Tech Stack')),
                ('link', models.URLField(blank=True, verbose_name='Project Link')),
                ('github', models.URLField(blank=True, verbose_name='GitHub Link')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image 3')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
